---
- name: Pull docker images 
  hosts: all
  tasks:

    - name: Copy Docker Compose File
      copy:
        src: ./docker-compose.yml
        dest: ./
    - name: Pull Images
      command: docker-compose pull

    - name: Running Docker Compose File
      command: docker-compose -f docker-compose.yml up -d
